config/routes.rb
InboxItems::Engine.routes.draw do

  resources :inbox_items, path: '/' do
  	member do
  		get :file_redirect
  	end
  end
  
end

app/models/inbox_item.rb
require 'aasm'

class InboxItem < ActiveRecord::Base
  include AASM

	belongs_to :user
  belongs_to :log_entry
  has_many :file_uploads

  attr_accessor :convert, :project_id, :log_time, :log_type, :date
      
  aasm whiny_transitions: true  do
    state :unread, initial: true
    state :read
    state :converted
    event :mark_as_read do
      transitions from: :unread, to: :read
    end
    event :convert_to_log_item do
      transitions from: :read, to: :converted
      before do
        do_conversion
      end
    end
  end

  def do_conversion
    transaction do
      project = user.projects.find(project_id)

    	l = project.log_entries.build({
        user_id: user.id,
  			log_time: self.log_time,
        date: self.date,
        log_type: self.log_type,
  			task_name: self.subject,
  			task_description: self.body,
        technical_risks: project.technical_risks
  			})
      
  		l.save!
      update_attribute(:log_entry_id, l.id)
      file_uploads.update_all(log_entry_id: l.id)
    end
  end

  def self.unread
    where(aasm_state: 'unread')
  end
  
  def self.unconverted
    where(aasm_state: ['unread', 'read'])
  end

  def title
    subject
  end

end

app/controllers/inbox_items/application_controller.rb
class InboxItems::ApplicationController < ApplicationController
end

app/controllers/inbox_items/inbox_items_controller.rb
module InboxItems
	class InboxItemsController < ApplicationController

		def index
			@inbox_items = current_user.inbox_items.order(id: :desc).unconverted.all
		end

		def edit
			@inbox_item = current_user.inbox_items.find(params[:id])
			@inbox_item.mark_as_read! if @inbox_item.may_mark_as_read?
			@inbox_item.convert = true unless @inbox_item.converted?
			@inbox_item.log_type = 'lab_notes'
			@inbox_item.date = @inbox_item.created_at.to_date
			@projects = current_user.projects.not_archived.not_deleted.all.collect { |p| [p.project_name, p.id] }
			@inbox_item.project_id = @projects.first[1] if @projects.count == 1
		end

		def update
			@inbox_item = current_user.inbox_items.find(params[:id])
			
			if @inbox_item.update_attributes(item_params)
				@inbox_item.convert_to_log_item! if item_params[:convert] == '1'
				redirect_to inbox_items_path, notice: 'Updated'
			end
		end

		def destroy
			@inbox_item = current_user.inbox_items.find(params[:id])
			@inbox_item.destroy
			redirect_to inbox_items_path, notice: t(:inbox_item_was_removed)
		end
		
		def file_redirect
			@inbox_item = current_user.inbox_items.find(params[:id])
			@file_upload = @inbox_item.file_uploads.find(params[:file_upload_id])
			redirect_to @file_upload.public_url if @file_upload.url.present?
		end

		def item_params
			params.require(:inbox_item).permit(:subject, :body, :project_id, :log_time, :convert, :log_type, :date)
		end
		private :item_params

	end
end

	 

app/helpers/inbox_items/application_helper.rb
module InboxItems
  module ApplicationHelper
  end
end

app/views/inbox_items/inbox_items/_inbox_item.html.haml
%tr{data: { toggle: 'collapse', target: "#collapse_#{inbox_item.id}"}, class: "#{'unread' if inbox_item.unread?}" }

	%td.subject= link_to inbox_item.subject, edit_inbox_item_path(inbox_item)
	%td.body
		= inbox_item.body
		%div.collapse.collapse-panel{id: "collapse_#{inbox_item.id}"}
			- if inbox_item.file_uploads.any?
				%ul.list-unstyled
					- inbox_item.file_uploads.each do |file|
						%li= link_to file.filename, file_redirect_inbox_item_path(inbox_item, file_upload_id: file.id), target: '_blank'

	%td.file.text-center= glyph(:file) if inbox_item.file_uploads.present?
	%td.edit.text-center
		= link_to edit_inbox_item_path(inbox_item), title: t(:edit) do
			%span.glyphicon.glyphicon-import
	%td.remove.text-center
		= link_to inbox_item_path(inbox_item), method: :delete, data:{confirm: t(:are_you_sure)}, title: t(:remove) do
			= content_tag :i, nil, class: 'ion-close-circled'

app/views/inbox_items/inbox_items/edit.html.haml
:css
  .unread * {
    font-weight: bold;
  }
  #conversion {
    -webkit-transition: opacity 0.25s;
    transition: opacity 0.25s;
  }
  #conversion.invisible {
    opacity: 0;
  }

%br
.alert.alert-info Feel free to edit this email into a more concise log

= simple_nested_form_for @inbox_item do |f|
  .menubar
    .sidebar-toggler.visible-xs
      %i.ion-navicon
    .page-title= t(:inbox)
  .content-wrapper
    .row
      .col-sm-12= f.input :subject
      .col-sm-12= f.input :body, input_html: {rows: 4}
    
    - unless @inbox_item.converted? 
      .row
        .col-sm-3   
          = f.label :convert, 'Import'
          %br
          = f.check_box :convert, data: {target: '#conversion'}, class: 'switch'
          %br
        #conversion.col-sm-9
          .row
            .col-sm-4= f.input :project_id, collection: @projects, prompt: 'Project...', input_html: {class: 'chosen'} 
            .col-sm-4= f.input :date, input_html: {class: 'datepicker'}
            .col-sm-4
              %br
              .btn-group{data:{toggle: 'buttons'}}
                %label.btn-xs.btn.btn-primary{class: "#{'active' if f.object.log_type == 'lab_notes'}"}
                  = f.radio_button :log_type, 'lab_notes', autocomplete: 'off'
                  = t(:lab_notes)
                %label.btn.btn-xs.btn-primary{class: "#{'active' if f.object.log_type == 'log_data'}"}
                  = f.radio_button :log_type, 'log_data', autocomplete: 'off'
                  = t(:log_data)
                %label.btn.btn-xs.btn-primary{class: "#{'active' if f.object.log_type == 'progress'}"} 
                  = f.radio_button :log_type, 'progress', autocomplete: 'off'
                  = t(:progress)

    %hr
    = f.submit 'Convert', class: 'btn btn-success', disable_with: t('please_wait')

app/views/inbox_items/inbox_items/index.html.haml
.menubar
	.sidebar-toggler.visible-xs
		%i.ion-navicon
	.page-title= t(:inbox)

.content-wrapper
	%br
	- if @inbox_items.blank?
		%h2= t(:no_items_found)
	- else
		.chart
			.table-responsive
				%table#inbox_items.table.table-striped
					%thead
						%tr
							%th= t(:subject)
							%th= t(:body)
							%th.text-center= t(:file)
							%th.text-center= t(:import)
							%th.text-center= t(:delete)
					%tbody= render @inbox_items

= content_for :body_id, "reports"